[Client]
	addr = "127.0.0.1:3306"
	dsn = "root:znhkp123@tcp(127.0.0.1:3306)/clip_mng?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["root:znhkp123@tcp(127.0.0.1:3306)/clip_mng?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
